// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TKS.Data;

#nullable disable

namespace TKS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250529015851_RemoveForgeinkey")]
    partial class RemoveForgeinkey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TKS.Models.DonViTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<string>("Ten_Don_Vi_Tinh")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Ten_Don_Vi_Tinh")
                        .IsUnique();

                    b.ToTable("tbl_DM_Don_Vi_Tinh");
                });

            modelBuilder.Entity("TKS.Models.Kho", b =>
                {
                    b.Property<int>("Kho_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Kho_Id"));

                    b.Property<string>("Ghi_Chu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ten_Kho")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Kho_Id");

                    b.HasIndex("Ten_Kho")
                        .IsUnique();

                    b.ToTable("tbl_DM_Kho");
                });

            modelBuilder.Entity("TKS.Models.KhoUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kho_Id")
                        .HasColumnType("int");

                    b.Property<string>("Ma_Dang_Nhap")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tbl_DM_Kho_User");
                });

            modelBuilder.Entity("TKS.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<string>("Ma_LSP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ten_LSP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Ma_LSP", "Ten_LSP")
                        .IsUnique();

                    b.ToTable("tbl_DM_Loai_San_Pham");
                });

            modelBuilder.Entity("TKS.Models.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<string>("Ma_NCC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ten_NCC")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Ten_NCC")
                        .IsUnique();

                    b.ToTable("tbl_DM_NCC");
                });

            modelBuilder.Entity("TKS.Models.NhapKho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ghi_Chu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Kho_ID")
                        .HasColumnType("int");

                    b.Property<int>("NCC_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Nhap_Kho")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("So_Phieu_Nhap_Kho")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("So_Phieu_Nhap_Kho")
                        .IsUnique();

                    b.ToTable("tbl_DM_Nhap_Kho");
                });

            modelBuilder.Entity("TKS.Models.NhapKhoRaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Don_Gia_Nhap")
                        .HasColumnType("double");

                    b.Property<int>("Nhap_Kho_ID")
                        .HasColumnType("int");

                    b.Property<int>("SL_Nhap")
                        .HasColumnType("int");

                    b.Property<int>("San_Pham_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_DM_Nhap_Kho_Raw_Data");
                });

            modelBuilder.Entity("TKS.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Don_Vi_Tinh_ID")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<int>("Loai_San_Pham_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ma_San_Pham")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ten_San_Pham")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Loai_San_Pham_ID", "Ten_San_Pham", "Ma_San_Pham", "Don_Vi_Tinh_ID")
                        .IsUnique();

                    b.ToTable("tbl_DM_San_Pham");
                });

            modelBuilder.Entity("TKS.Models.XNK_Nhap_Kho", b =>
                {
                    b.Property<string>("So_Phieu_Nhap_Kho")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Kho")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NCC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Ngay_Nhap_Kho")
                        .HasColumnType("datetime(6)");

                    b.HasKey("So_Phieu_Nhap_Kho");

                    b.ToTable("tbl_XNK_Nhap_Kho");
                });

            modelBuilder.Entity("TKS.Models.XuatKho", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ghi_Chu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Kho_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Xuat_Kho")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("So_Phieu_Xuat_Kho")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("tbl_DM_Xuat_Kho");
                });

            modelBuilder.Entity("TKS.Models.XuatKhoRaw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Don_Gia_Xuat")
                        .HasColumnType("double");

                    b.Property<int>("SL_Xuat")
                        .HasColumnType("int");

                    b.Property<int>("San_Pham_ID")
                        .HasColumnType("int");

                    b.Property<int>("Xuat_Kho_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_DM_Xuat_Kho_Raw_Data");
                });
#pragma warning restore 612, 618
        }
    }
}
