// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TKS.Data;

#nullable disable

namespace TKS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250523022215_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TKS.Models.DonViTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ten_Don_Vi_Tinh")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Ten_Don_Vi_Tinh");

                    b.ToTable("tbl_DM_Don_Vi_Tinh");
                });

            modelBuilder.Entity("TKS.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<string>("Ma_LSP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ten_LSP")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Ma_LSP", "Ten_LSP");

                    b.ToTable("tbl_DM_Loai_San_Pham");
                });

            modelBuilder.Entity("TKS.Models.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<string>("Ma_NCC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ten_NCC")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Ten_NCC");

                    b.ToTable("tbl_DM_NCC");
                });

            modelBuilder.Entity("TKS.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Don_Vi_Tinh_ID")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<int>("Loai_San_Pham_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ma_San_Pham")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ten_San_Pham")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Don_Vi_Tinh_ID");

                    b.HasIndex("Loai_San_Pham_ID", "Ten_San_Pham", "Ma_San_Pham", "Don_Vi_Tinh_ID");

                    b.ToTable("tbl_DM_San_Pham");
                });

            modelBuilder.Entity("TKS.Models.SanPham", b =>
                {
                    b.HasOne("TKS.Models.DonViTinh", "donViTinh")
                        .WithMany()
                        .HasForeignKey("Don_Vi_Tinh_ID")
                        .IsRequired();

                    b.HasOne("TKS.Models.LoaiSanPham", "loaiSanPham")
                        .WithMany()
                        .HasForeignKey("Loai_San_Pham_ID")
                        .IsRequired();

                    b.Navigation("donViTinh");

                    b.Navigation("loaiSanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
